[package]
name = "match-program"
version = "0.0.1"
description = "x1-games Match program — escrow + settlement for wagered matches"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "match_program"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "1.0.2"
game-registry = { path = "../game-registry", features = ["no-entrypoint"] }
